//
//  MAMovieDetailConfigurator.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension MAMovieDetailInteractor: MAMovieDetailViewControllerOutput {
}

extension MAMovieDetailPresenter: MAMovieDetailInteractorOutput {
}

class MAMovieDetailConfigurator {
    // MARK: - Object lifecycle
  
    static let sharedInstance = MAMovieDetailConfigurator()
  
    private init() {

    }
  
    // MARK: - Configuration
  
    func configure(viewController: MAMovieDetailViewController) {
      let router = MAMovieDetailRouter()
      router.viewController = viewController
      
      let presenter = MAMovieDetailPresenter()
      presenter.output = viewController
      
      let interactor = MAMovieDetailInteractor()
      interactor.output = presenter
      
      viewController.output = interactor
      viewController.router = router
    }
}
