//
//  MAMovieDetailInteractor.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MAMovieDetailInteractorInput {
    func doSomething(request: MAMovieDetail.Request)
    var movie : MAMovieModel! { get set }
}

protocol MAMovieDetailInteractorOutput {
    func presentSomething(response: MAMovieDetail.Response)
}

class MAMovieDetailInteractor: MAMovieDetailInteractorInput {
    var output: MAMovieDetailInteractorOutput?
    var worker: MAMovieDetailWorker?
    var movie: MAMovieModel!

    // MARK: - Business logic

    func doSomething(request: MAMovieDetail.Request) {
        // NOTE: Create some Worker to do the work

    }
    
    func doLoadData(request: MAMovieDetail.Request.UI) {
        weak var weakSelf = self
        
        if worker == nil {
            worker = MAMovieDetailWorker.init(withTableView: request.tblView, movie: self.movie)
        }
    }
}
