//
//  MAMovieDetailPresenter.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MAMovieDetailPresenterInput {
  	func presentSomething(response: MAMovieDetail.Response)
}

protocol MAMovieDetailPresenterOutput: class {
  	func displaySomething(viewModel: MAMovieDetail.ViewModel)
}

class MAMovieDetailPresenter: MAMovieDetailPresenterInput {
    weak var output: MAMovieDetailPresenterOutput?

    // MARK: - Presentation logic


    func presentSomething(response: MAMovieDetail.Response) {
	    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
	    let viewModel = MAMovieDetail.ViewModel()
	    output?.displaySomething(viewModel: viewModel)
    }
}
