//
//  MAMoviesPresenter.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MAMoviesPresenterInput {
  	func presentSomething(response: MAMovies.Response)
}

protocol MAMoviesPresenterOutput: class {
  	func displaySomething(viewModel: MAMovies.ViewModel)
    func displayMovieDetail(viewModel : MAMovies.ViewModel.ViewMovie)
}

class MAMoviesPresenter: MAMoviesPresenterInput {
    weak var output: MAMoviesPresenterOutput?

    // MARK: - Presentation logic


    func presentSomething(response: MAMovies.Response) {
	    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
	    let viewModel = MAMovies.ViewModel()
	    output?.displaySomething(viewModel: viewModel)
    }
    
    func presentMovieDetail(response: MAMovies.Response.ViewMovie) {
        let viewModel = MAMovies.ViewModel.ViewMovie(res: response)
        output?.displayMovieDetail(viewModel: viewModel)
    }
}
