//
//  MAMoviesViewController.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Localize_Swift

protocol MAMoviesViewControllerInput {
    func displaySomething(viewModel: MAMovies.ViewModel)
}

protocol MAMoviesViewControllerOutput {
    func doSomething(request: MAMovies.Request)
    func doLoadData(request : MAMovies.Request.UI)
}

class MAMoviesViewController: UIViewController, MAMoviesViewControllerInput {
    var output: MAMoviesViewControllerOutput?
    var router: MAMoviesRouter?
    
    @IBOutlet weak var tblView : UITableView!
    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        MAMoviesConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        self.setBackButtonForNextChildItemInNavigationWithTitle("")
        doSomethingOnLoad()
    }

    // MARK: - Event handling

    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work

        self.title = "Movies.Title".localized().uppercased()
        
        let request = MAMovies.Request.UI(tblView: self.tblView)
        output?.doLoadData(request: request)
    }

    // MARK: - Display logic

    func displaySomething(viewModel: MAMovies.ViewModel) {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
    
    func displayMovieDetail(viewModel: MAMovies.ViewModel.ViewMovie) {
        router?.navigateToMovieDetail(viewModel.res.movie)
    }
}

extension MAMoviesViewController: MAMoviesPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(segue: segue)
    }
}
