//
//  MAMoviesModels.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct MAMovies {
  	
  	struct Request {
        struct UI {
            var tblView : UITableView
        }
    }

    struct Response {
        struct ViewMovie {
            var movie : MAMovieModel
        }
    }

    struct ViewModel {
        struct ViewMovie {
            var res : Response.ViewMovie
        }
    }
}
