//
//  MAMoviesInteractor.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MAMoviesInteractorInput {
    func doSomething(request: MAMovies.Request)
}

protocol MAMoviesInteractorOutput {
    func presentSomething(response: MAMovies.Response)
    func presentMovieDetail(response : MAMovies.Response.ViewMovie)
}

class MAMoviesInteractor: MAMoviesInteractorInput {
    var output: MAMoviesInteractorOutput?
    var worker: MAMoviesWorker?

    // MARK: - Business logic

    func doSomething(request: MAMovies.Request) {
        // NOTE: Create some Worker to do the work

      

        // NOTE: Pass the result to the Presenter

        let response = MAMovies.Response()
        output?.presentSomething(response: response)
    }
    
    func doLoadData(request: MAMovies.Request.UI) {
        weak var weakSelf = self
        
        if worker == nil {
            worker = MAMoviesWorker.init(withTableView: request.tblView)
            worker?.viewDetailMovie = weakSelf?.viewDetailMovie
        }
    }
    
    private func viewDetailMovie(_ movie : MAMovieModel) {
        let res = MAMovies.Response.ViewMovie(movie: movie)
        self.output?.presentMovieDetail(response: res)
    }
}
