//
//  MAMoviesConfigurator.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension MAMoviesInteractor: MAMoviesViewControllerOutput {
}

extension MAMoviesPresenter: MAMoviesInteractorOutput {
}

class MAMoviesConfigurator {
    // MARK: - Object lifecycle
  
    static let sharedInstance = MAMoviesConfigurator()
  
    private init() {

    }
  
    // MARK: - Configuration
  
    func configure(viewController: MAMoviesViewController) {
      let router = MAMoviesRouter()
      router.viewController = viewController
      
      let presenter = MAMoviesPresenter()
      presenter.output = viewController
      
      let interactor = MAMoviesInteractor()
      interactor.output = presenter
      
      viewController.output = interactor
      viewController.router = router
    }
    
    
}
