//
//  MAWebViewViewController.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MAWebViewViewControllerInput {
    func displaySomething(viewModel: MAWebView.ViewModel)
}

protocol MAWebViewViewControllerOutput {
    func doSomething(request: MAWebView.Request)
    func loadWebView(request : MAWebView.Request.UI)
    func loadUrl(request : MAWebView.Request.LoadUrl)
}

class MAWebViewViewController: UIViewController, MAWebViewViewControllerInput {
    var output: MAWebViewViewControllerOutput?
    var router: MAWebViewRouter?

    @IBOutlet weak var webView : UIWebView!
    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        MAWebViewConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomethingOnLoad()
        
        self.title = "Booking".localized().uppercased()
        
        let requestUI = MAWebView.Request.UI(webView: self.webView)
        self.output?.loadWebView(request: requestUI)
        
        let requestLoadUrl = MAWebView.Request.LoadUrl(url: "https://www.cathaycineplexes.com.sg/")
        
        self.output?.loadUrl(request: requestLoadUrl)
        
        
    }

    // MARK: - Event handling

    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work

        let request = MAWebView.Request()
        output?.doSomething(request: request)
    }

    // MARK: - Display logic

    func displaySomething(viewModel: MAWebView.ViewModel) {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}

extension MAWebViewViewController: MAWebViewPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(segue: segue)
    }
}
