//
//  MAWebViewConfigurator.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension MAWebViewInteractor: MAWebViewViewControllerOutput {
}

extension MAWebViewPresenter: MAWebViewInteractorOutput {
}

class MAWebViewConfigurator {
    // MARK: - Object lifecycle
  
    static let sharedInstance = MAWebViewConfigurator()
  
    private init() {

    }
  
    // MARK: - Configuration
  
    func configure(viewController: MAWebViewViewController) {
      let router = MAWebViewRouter()
      router.viewController = viewController
      
      let presenter = MAWebViewPresenter()
      presenter.output = viewController
      
      let interactor = MAWebViewInteractor()
      interactor.output = presenter
      
      viewController.output = interactor
      viewController.router = router
    }
}
