//
//  MAWebViewModels.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct MAWebView {
  	
  	struct Request {

    }

    struct Response {

    }

    struct ViewModel {
    
    }
}
