//
//  MAWebViewPresenter.swift
//  Movies
//
//  Created by admin on 8/5/17.
//  Copyright (c) 2017 Tri Vo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MAWebViewPresenterInput {
  	func presentSomething(response: MAWebView.Response)
}

protocol MAWebViewPresenterOutput: class {
  	func displaySomething(viewModel: MAWebView.ViewModel)
}

class MAWebViewPresenter: MAWebViewPresenterInput {
    weak var output: MAWebViewPresenterOutput?

    // MARK: - Presentation logic


    func presentSomething(response: MAWebView.Response) {
	    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
	    let viewModel = MAWebView.ViewModel()
	    output?.displaySomething(viewModel: viewModel)
    }
}
